//! Test framework for SVT-AV1 Rust port.
//!
//! Provides utilities for loading golden test data generated by the C++ test suite,
//! comparing Rust output against C reference output, and testing across SIMD dispatch levels.

use std::fs;
use std::path::{Path, PathBuf};

/// Golden test data: input/output pair from C reference.
#[derive(Debug)]
pub struct GoldenData {
    pub input: Vec<u8>,
    pub output: Vec<u8>,
    pub name: String,
}

/// Load golden test data generated by the C++ test suite.
///
/// Files are expected at `test/golden/<component>/<test_name>.bin`
/// Format: [input_len:u32le][input_data][output_len:u32le][output_data]
pub fn load_golden(component: &str, test_name: &str) -> Option<GoldenData> {
    let path = golden_path(component, test_name);
    let data = fs::read(&path).ok()?;

    if data.len() < 4 {
        return None;
    }

    let input_len = u32::from_le_bytes([data[0], data[1], data[2], data[3]]) as usize;
    let input_end = 4 + input_len;

    if data.len() < input_end + 4 {
        return None;
    }

    let output_len =
        u32::from_le_bytes([data[input_end], data[input_end + 1], data[input_end + 2], data[input_end + 3]])
            as usize;
    let output_start = input_end + 4;
    let output_end = output_start + output_len;

    if data.len() < output_end {
        return None;
    }

    Some(GoldenData {
        input: data[4..input_end].to_vec(),
        output: data[output_start..output_end].to_vec(),
        name: format!("{component}/{test_name}"),
    })
}

/// Get the path to a golden data file.
pub fn golden_path(component: &str, test_name: &str) -> PathBuf {
    // Walk up from the workspace root to find the SVT-AV1 repo root
    let workspace = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace root");
    workspace
        .parent()
        .expect("svtav1 repo root")
        .join("test")
        .join("golden")
        .join(component)
        .join(format!("{test_name}.bin"))
}

/// Compare Rust output against C golden data with exact match.
pub fn assert_parity(rust_output: &[u8], golden: &GoldenData) {
    assert_eq!(
        rust_output.len(),
        golden.output.len(),
        "Output length mismatch for {}",
        golden.name,
    );
    assert_eq!(
        rust_output, &golden.output[..],
        "Output data mismatch for {}",
        golden.name,
    );
}

/// Compare with tolerance for floating-point paths.
/// `ulp_tolerance` is the maximum number of ULPs (units in the last place) of difference.
pub fn assert_parity_f64(rust: &[f64], golden: &[f64], ulp_tolerance: u64) {
    assert_eq!(rust.len(), golden.len(), "Length mismatch");

    for (i, (&r, &g)) in rust.iter().zip(golden.iter()).enumerate() {
        let r_bits = r.to_bits();
        let g_bits = g.to_bits();
        let ulp_diff = r_bits.abs_diff(g_bits);
        assert!(
            ulp_diff <= ulp_tolerance,
            "Float mismatch at index {i}: rust={r}, golden={g}, ulp_diff={ulp_diff} > tolerance={ulp_tolerance}",
        );
    }
}

/// Compare f32 arrays with ULP tolerance.
pub fn assert_parity_f32(rust: &[f32], golden: &[f32], ulp_tolerance: u32) {
    assert_eq!(rust.len(), golden.len(), "Length mismatch");

    for (i, (&r, &g)) in rust.iter().zip(golden.iter()).enumerate() {
        let r_bits = r.to_bits();
        let g_bits = g.to_bits();
        let ulp_diff = r_bits.abs_diff(g_bits);
        assert!(
            ulp_diff <= ulp_tolerance,
            "Float mismatch at index {i}: rust={r}, golden={g}, ulp_diff={ulp_diff} > tolerance={ulp_tolerance}",
        );
    }
}

/// Compare i32 arrays (transform coefficients, etc.) with exact match.
pub fn assert_parity_i32(rust: &[i32], golden: &[i32]) {
    assert_eq!(rust.len(), golden.len(), "Length mismatch");

    for (i, (&r, &g)) in rust.iter().zip(golden.iter()).enumerate() {
        assert_eq!(
            r, g,
            "Coefficient mismatch at index {i}: rust={r}, golden={g}",
        );
    }
}
